create table economic_policy(
    id serial primary key,
    country_name varchar(200),
    country_code varchar(200),
    time integer,
    time_code varchar(200),
    agriculture_value_added__of_gdp real,
    exports_of_goods_and_services__of_gdp real,
    external_debt_stocks_total_dod_current_us real,
    foreign_direct_investment_net_inflows_bop_current_us real,
    gdp_current_us real,
    gdp_growth_annual real,
    gni_per_capita_ppp_current_international real,
    gni_ppp_current_international real,
    imports_of_goods_and_services__of_gdp real,
    industry_value_added__of_gdp real,
    net_official_development_assistance_and_official_aid_received real,
    total_debt_service__of_exports_of_goods_services_and_primary real,
    adjusted_net_national_income_annual__growth real,
    adjusted_net_national_income_current_us real,
    adjusted_net_national_income_per_capita_constant_2010_us real,
    adjusted_net_savings_excluding_particulate_emission_damage__of real,
    adjusted_net_savings_excluding_particulate_emission_damage_cur real,
    agriculture_value_added_annual__growth real,
    average_interest_on_new_external_debt_commitments_official real,
    average_maturity_on_new_external_debt_commitments_years real,
    charges_for_the_use_of_intellectual_property_payments_bop_curr real,
    chemicals__of_value_added_in_manufacturing real,
    charges_for_the_use_of_intellectual_property_receipts_bop_curr real,
    commitments_public_and_publicly_guaranteed_com_current_us real,
    current_account_balance__of_gdp real,
    current_account_balance_bop_current_us real,
    debt_forgiveness_or_reduction_current_us real,
    debt_service_to_exports real,
    debt_service_on_external_debt_private_nonguaranteed_png__tds_c real,
    debt_service_on_external_debt_total_tds_current_us real,
    debt_service_on_external_debt_public_and_publicly_guaranteed_p real,
    debt_stock_reduction_current_us real,
    exports_of_goods_and_services_annual__growth real,
    exports_of_goods_and_services_bop_current_us real,
    external_debt_stocks_public_and_publicly_guaranteed_ppg__dod real,
    external_debt_stocks_private_nonguaranteed_png__dod_current_us real,
    final_consumption_expenditure__of_gdp real,
    final_consumption_expenditure_annual__growth real,
    foreign_direct_investment_net_outflows_bop_current_us real,
    foreign_direct_investment_net_outflows__of_gdp real,
    foreign_direct_investment_net_inflows__of_gdp real,
    general_government_final_consumption_expenditure__of_gdp real,
    general_government_final_consumption_expenditure_annual__growth real,
    gni_growth_annual real,
    gdp_ppp_current_international real,
    gni_current_us real,
    gdp_per_capita_ppp_current_international real,
    gross_capital_formation_annual__growth real,
    gross_capital_formation_current_us real,
    gross_domestic_savings__of_gdp real,
    gross_savings__of_gdp real,
    imports_of_goods_and_services_annual__growth real,
    imports_of_goods_and_services_bop_current_us real,
    industry_value_added_annual__growth real,
    machinery_and_transport_equipment__of_value_added_in_manufact real,
    manufacturing_value_added__of_gdp real,
    manufacturing_value_added_annual__growth real,
    net_financial_account_bop_current_us real,
    net_trade_in_goods_and_services_bop_current_us real,
    portfolio_investment_net_bop_current_us real,
    price_level_ratio_of_ppp_conversion_factor_gdp_to_market_exch real,
    primary_income_payments_bop_current_us real,
    primary_income_on_fdi_current_us real,
    primary_income_receipts_bop_current_us real,
    principal_repayments_on_external_debt_private_nonguaranteed_png real,
    principal_repayments_on_external_debt_public_and_publicly_guar real,
    reserves_and_related_items_bop_current_us real,
    secondary_income_receipts_bop_current_us real,
    services_value_added_annual__growth real,
    services_value_added_current_us real,
    textiles_and_clothing__of_value_added_in_manufacturing real,
    total_change_in_external_debt_stocks_current_us real,
    total_debt_service__of_gni real,
    total_reserves_includes_gold_current_us real,
    total_amount_of_debt_rescheduled_current_us real,
    undisbursed_external_debt_private_creditors_und_current_us real,
    undisbursed_external_debt_official_creditors_und_current_us real,
    undisbursed_external_debt_total_und_current_us real
);

comment on column economic_policy.net_official_development_assistance_and_official_aid_received is 'net_official_development_assistance_and_official_aid_received_current_us';
comment on column economic_policy.total_debt_service__of_exports_of_goods_services_and_primary is 'total_debt_service__of_exports_of_goods_services_and_primary_income';
comment on column economic_policy.adjusted_net_savings_excluding_particulate_emission_damage__of is 'adjusted_net_savings_excluding_particulate_emission_damage__of_gni';
comment on column economic_policy.adjusted_net_savings_excluding_particulate_emission_damage_cur is 'adjusted_net_savings_excluding_particulate_emission_damage_current_us';
comment on column economic_policy.charges_for_the_use_of_intellectual_property_payments_bop_curr is 'charges_for_the_use_of_intellectual_property_payments_bop_current_us';
comment on column economic_policy.charges_for_the_use_of_intellectual_property_receipts_bop_curr is 'charges_for_the_use_of_intellectual_property_receipts_bop_current_us';
comment on column economic_policy.debt_service_on_external_debt_private_nonguaranteed_png__tds_c is 'debt_service_on_external_debt_private_nonguaranteed_png__tds_current_us';
comment on column economic_policy.debt_service_on_external_debt_public_and_publicly_guaranteed_p is 'debt_service_on_external_debt_public_and_publicly_guaranteed_ppg__tds_current_us';
comment on column economic_policy.external_debt_stocks_public_and_publicly_guaranteed_ppg__dod is 'external_debt_stocks_public_and_publicly_guaranteed_ppg__dod_current_us';
comment on column economic_policy.machinery_and_transport_equipment__of_value_added_in_manufact is 'machinery_and_transport_equipment__of_value_added_in_manufacturing';
comment on column economic_policy.price_level_ratio_of_ppp_conversion_factor_gdp_to_market_exch is 'price_level_ratio_of_ppp_conversion_factor_gdp_to_market_exchange_rate';
comment on column economic_policy.principal_repayments_on_external_debt_private_nonguaranteed_png is 'principal_repayments_on_external_debt_private_nonguaranteed_png__amt_current_us';
comment on column economic_policy.principal_repayments_on_external_debt_public_and_publicly_guar is 'principal_repayments_on_external_debt_public_and_publicly_guaranteed_ppg__amt_current_us';
