create table social_protection(
    id serial primary key,
    country_name varchar(200),
    country_code varchar(200),
    time integer,
    time_code varchar(200),
    adequacy_of_social_insurance_programs__of_total_welfare_of real,
    adequacy_of_social_safety_net_programs__of_total_welfare_of real,
    average_working_hours_of_children_study_and_work_ages_7_14 real,
    adequacy_of_social_protection_and_labor_programs__of_total real,
    adequacy_of_unemployment_benefits_and_almp__of_total_welfare_of real,
    average_working_hours_of_children_working_only_ages_7_14_hours real,
    children_in_employment_total__of_children_ages_7_14 real,
    coverage_of_social_insurance_programs__of_population real,
    coverage_of_social_protection_and_labor_programs__of_population real,
    coverage_of_social_safety_net_programs__of_population real,
    coverage_of_unemployment_benefits_and_almp__of_population real,
    employers_female__of_female_employment__modeled_ilo_estimate real,
    employers_total__of_total_employment__modeled_ilo_estimate real,
    employment_in_industry__of_total_employment__modeled_ilo real,
    employment_to_population_ratio_15__total___modeled_ilo_estimate real,
    employment_to_population_ratio_ages_15_24_total___modeled_ilo real,
    employers_male__of_male_employment__modeled_ilo_estimate real,
    employment_in_agriculture__of_total_employment__modeled_ilo real,
    employment_in_services__of_total_employment__modeled_ilo real,
    informal_employment__of_total_non_agricultural_employment real,
    international_migrant_stock_total bigint,
    gdp_per_person_employed_constant_2011_ppp real,
    international_migrant_stock__of_population real,
    labor_force_participation_rate_for_ages_15_24_total___modeled real,
    labor_force_participation_rate_total__of_total_population_ages real,
    labor_force_with_advanced_education__of_total_working_age real,
    labor_force_with_intermediate_education__of_total_working_age real,
    labor_force_with_basic_education__of_total_working_age_popul real,
    labor_force_total bigint,
    net_migration bigint,
    self_employed_total__of_total_employment__modeled_ilo_estimate real,
    share_of_youth_not_in_education_employment_or_training_total real,
    unemployment_with_advanced_education__of_total_labor_force real,
    unemployment_with_intermediate_education__of_total_labor_force real,
    unemployment_with_basic_education__of_total_labor_force_with real,
    unemployment_total__of_total_labor_force__modeled_ilo_estimate real,
    unemployment_youth_total__of_total_labor_force_ages_15_24__mo real
);

comment on column social_protection.adequacy_of_social_insurance_programs__of_total_welfare_of is 'adequacy_of_social_insurance_programs__of_total_welfare_of_beneficiary_households';
comment on column social_protection.adequacy_of_social_safety_net_programs__of_total_welfare_of is 'adequacy_of_social_safety_net_programs__of_total_welfare_of_beneficiary_households';
comment on column social_protection.average_working_hours_of_children_study_and_work_ages_7_14 is 'average_working_hours_of_children_study_and_work_ages_7_14_hours_per_week';
comment on column social_protection.adequacy_of_social_protection_and_labor_programs__of_total is 'adequacy_of_social_protection_and_labor_programs__of_total_welfare_of_beneficiary_households';
comment on column social_protection.adequacy_of_unemployment_benefits_and_almp__of_total_welfare_of is 'adequacy_of_unemployment_benefits_and_almp__of_total_welfare_of_beneficiary_households';
comment on column social_protection.average_working_hours_of_children_working_only_ages_7_14_hours is 'average_working_hours_of_children_working_only_ages_7_14_hours_per_week';
comment on column social_protection.employment_in_industry__of_total_employment__modeled_ilo is 'employment_in_industry__of_total_employment__modeled_ilo_estimate';
comment on column social_protection.employment_to_population_ratio_ages_15_24_total___modeled_ilo is 'employment_to_population_ratio_ages_15_24_total___modeled_ilo_estimate';
comment on column social_protection.employment_in_agriculture__of_total_employment__modeled_ilo is 'employment_in_agriculture__of_total_employment__modeled_ilo_estimate';
comment on column social_protection.employment_in_services__of_total_employment__modeled_ilo is 'employment_in_services__of_total_employment__modeled_ilo_estimate';

comment on column social_protection.labor_force_participation_rate_for_ages_15_24_total___modeled is 'labor_force_participation_rate_for_ages_15_24_total___modeled_ilo_estimate';
comment on column social_protection.labor_force_participation_rate_total__of_total_population_ages is 'labor_force_participation_rate_total__of_total_population_ages_15__modeled_ilo_estimate';
comment on column social_protection.labor_force_with_advanced_education__of_total_working_age is 'labor_force_with_advanced_education__of_total_working_age_population_with_advanced_education';
comment on column social_protection.labor_force_with_intermediate_education__of_total_working_age is 'labor_force_with_intermediate_education__of_total_working_age_population_with_intermediate_education';
comment on column social_protection.labor_force_with_basic_education__of_total_working_age_popul is 'labor_force_with_basic_education__of_total_working_age_population_with_basic_education';

comment on column social_protection.share_of_youth_not_in_education_employment_or_training_total is 'share_of_youth_not_in_education_employment_or_training_total__of_youth_population';
comment on column social_protection.unemployment_with_advanced_education__of_total_labor_force is 'unemployment_with_advanced_education__of_total_labor_force_with_advanced_education';
comment on column social_protection.unemployment_with_intermediate_education__of_total_labor_force is 'unemployment_with_intermediate_education__of_total_labor_force_with_intermediate_education';
comment on column social_protection.unemployment_with_basic_education__of_total_labor_force_with is 'unemployment_with_basic_education__of_total_labor_force_with_basic_education';
comment on column social_protection.unemployment_youth_total__of_total_labor_force_ages_15_24__mo is 'unemployment_youth_total__of_total_labor_force_ages_15_24__modeled_ilo_estimate';
