create table fin_sector (
    `country_name` varchar(200),
    `country_code` varchar(200),
    `time` integer,
    `time_code` varchar(200),
    `broad_money_current_lcu` real,
    `broad_money__of_gdp` real,
    `broad_money_growth_annual` real,
    `broad_money_to_total_reserves_ratio` real,
    `claims_on_central_government_annual_growth_as__of_broad_money` real,
    `claims_on_central_government_etc___gdp` real,
    `claims_on_other_sectors_of_the_domestic_economy__of_gdp` real,
    `claims_on_private_sector_annual_growth_as__of_broad_money` real,
    `claims_on_other_sectors_of_the_domestic_economy_annual_growth_as` real comment 'claims_on_other_sectors_of_the_domestic_economy_annual_growth_as__of_broad_money',
    `bank_capital_to_assets_ratio` real,
    `bank_liquid_reserves_to_bank_assets_ratio` real,
    `bank_nonperforming_loans_to_total_gross_loans` real,
    `deposit_interest_rate` real,
    `domestic_credit_provided_by_financial_sector__of_gdp` real,
    `domestic_credit_to_private_sector_by_banks__of_gdp` real,
    `domestic_credit_to_private_sector__of_gdp` real,
    `gdp_deflator_base_year_varies_by_country` real,
    `gdp_deflator_linked_series_base_year_varies_by_country` real,
    `inflation_consumer_prices_annual` real,
    `inflation_gdp_deflator_annual` real,
    `inflation_gdp_deflator_linked_series_annual` real,
    `market_capitalization_of_listed_domestic_companies__of_gdp` real,
    `net_domestic_credit_current_lcu` real,
    `market_capitalization_of_listed_domestic_companies_current_us` real,
    `net_foreign_assets_current_lcu` real,
    `official_exchange_rate_lcu_per_us__period_average` real,
    `stocks_traded_total_value__of_gdp` real,
    `stocks_traded_turnover_ratio_of_domestic_shares` real,
    `stocks_traded_total_value_current_us` real,
    `s_p_global_equity_indices_annual__change` real
);
